export const ASSETS = {
  hero: {
    mainPhoto: "/assets/hero-main-photo.png",
    gridBg: "/assets/hero-grid-bg.svg",
    ellipseBg: "/assets/hero-ellipse-bg.svg",
  },
  avatars: {
    avatar1: "/assets/avatar-1.png",
    avatar2: "/assets/avatar-2.png",
    avatar3: "/assets/avatar-3.png",
    avatar4: "/assets/avatar-4.png",
    avatar5: "/assets/avatar-5.png",
    avatar6: "/assets/avatar-6.png",
    avatar7: "/assets/avatar-7.png",
    badgeBg: "/assets/avatar-badge-bg.svg",
  },
  shapes: {
    shape1: "/assets/3d-shape-1.png",
    shape2: "/assets/3d-shape-2.png",
    cone1: "/assets/3d-cone-1.png",
    cone2: "/assets/3d-cone-2.png",
    cone3: "/assets/3d-cone-3.png",
  },
  icons: {
    search: "/assets/icon-search.svg",
    menu: "/assets/icon-menu.svg",
    logo: "/assets/logo-icon.svg",
    star: "/assets/icon-star.svg",
    check: "/assets/icon-check.svg",
  },
  masks: {
    rect1: "/assets/mask-rect-1.png",
    rect2: "/assets/mask-rect-2.png",
  },
  partners: {
    partner1: "/assets/partner-1.svg",
    partner2: "/assets/partner-2.svg",
    partner3: "/assets/partner-3.svg",
    partner4: "/assets/partner-4.svg",
    partner5: "/assets/partner-5.svg",
  },
  categories: {
    design: "/assets/category-icon-1.svg",
    dev: "/assets/category-icon-2.svg",
    it: "/assets/category-icon-3.svg",
    business: "/assets/category-icon-4.svg",
    marketing: "/assets/category-icon-5.svg",
    photo: "/assets/category-icon-6.svg",
  },
  courses: {
    course1: "/assets/course-card-1.png",
    course2: "/assets/course-card-2.png",
    course3: "/assets/course-card-3.png",
    course4: "/assets/course-card-4.png",
    course5: "/assets/course-card-5.png",
    course6: "/assets/course-card-6.png",
  },
  growth: {
    student1: "/assets/growth-student-1.png",
    shape1: "/assets/growth-shape-1.png",
    student2: "/assets/growth-student-2.png",
    shape2: "/assets/growth-shape-2.png",
    bg: "/assets/growth-bg.svg",
  },
  cta: {
    shape1: "/assets/cta-shape-1.png",
    shape2: "/assets/cta-shape-2.png",
    shape3: "/assets/cta-shape-3.png",
    shape4: "/assets/cta-shape-4.png",
    shape5: "/assets/cta-shape-5.png",
    shape6: "/assets/cta-shape-6.png",
    grid: "/assets/cta-grid.svg",
  },
  testimonials: {
    bg: "/assets/testimonials-bg.svg",
  },
} as const;
